# Python 3.12 공식 이미지 사용
FROM python:3.12

# 컨테이너 내 작업 디렉토리 설정
WORKDIR /app

# requirements.txt 파일 복사
COPY auto_control_client/requirements.txt .

# 필요한 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# 소스 코드 복사
COPY auto_control_client/ .

# 애플리케이션 실행 명령
CMD ["python3", "main.py"]
