image: mcr.microsoft.com/windows/servercore:ltsc2019

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "8512546"
  ANDROID_HOME: "C:\android-sdk"
  JAVA_HOME: "C:\Program Files\Java\jdk-17"
  ANDROID_PROJECT_DIR: "Drtaa-Android"

before_script:
  - $ErrorActionPreference = "Stop"
  - $ProgressPreference = "SilentlyContinue"
  
  # Java 설치
  - Invoke-WebRequest -Uri "https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_windows-x64_bin.zip" -OutFile "openjdk.zip"
  - Expand-Archive -Path "openjdk.zip" -DestinationPath "C:\Program Files\Java\" -Force
  - Rename-Item -Path "C:\Program Files\Java\jdk-17" -NewName "C:\Program Files\Java\jdk-17"
  - $env:PATH += ";$env:JAVA_HOME\bin"
  
  # Android SDK 다운로드 및 설치
  - New-Item -ItemType Directory -Force -Path $env:ANDROID_HOME | Out-Null
  - Invoke-WebRequest -Uri "https://dl.google.com/android/repository/commandlinetools-win-${env:ANDROID_SDK_TOOLS}_latest.zip" -OutFile "commandlinetools.zip"
  - Expand-Archive -Path "commandlinetools.zip" -DestinationPath "$env:ANDROID_HOME" -Force
  - New-Item -ItemType Directory -Force -Path "$env:ANDROID_HOME\cmdline-tools" | Out-Null
  - Move-Item "$env:ANDROID_HOME\cmdline-tools" "$env:ANDROID_HOME\cmdline-tools\latest" -Force
  - $env:PATH += ";$env:ANDROID_HOME\cmdline-tools\latest\bin;$env:ANDROID_HOME\platform-tools"

  # SDK 컴포넌트 설치
  - Write-Host "y" | sdkmanager.bat --sdk_root=$env:ANDROID_HOME "platforms;android-$env:ANDROID_COMPILE_SDK" "build-tools;$env:ANDROID_BUILD_TOOLS" "platform-tools"
  
  # 프로젝트 디렉토리로 이동
  - cd $env:ANDROID_PROJECT_DIR
  
  # local.properties 파일 생성
  - Set-Content -Path "local.properties" -Value "sdk.dir=$env:ANDROID_HOME"
  - Add-Content -Path "local.properties" -Value "NAVER_MAP_CLIENT_ID=$env:NAVER_MAP_CLIENT_ID"
  - Add-Content -Path "local.properties" -Value "NAVER_MAP_CLIENT_ID_MANIFEST=$env:NAVER_MAP_CLIENT_ID_MANIFEST"
  - Add-Content -Path "local.properties" -Value "NAVER_MAP_CLIENT_SECRET=$env:NAVER_MAP_CLIENT_SECRET"
  - Add-Content -Path "local.properties" -Value "NAVER_CLIENT_ID=$env:NAVER_CLIENT_ID"
  - Add-Content -Path "local.properties" -Value "NAVER_CLIENT_SECRET=$env:NAVER_CLIENT_SECRET"
  - Add-Content -Path "local.properties" -Value "GOOGLE_LOGIN_CLIENT_ID=$env:GOOGLE_LOGIN_CLIENT_ID"
  - Add-Content -Path "local.properties" -Value "TOUR_API_KEY=$env:TOUR_API_KEY"
  - Add-Content -Path "local.properties" -Value "BASE_URL=$env:BASE_URL"
  - Add-Content -Path "local.properties" -Value "MQTT_URL=$env:MQTT_URL"
  - Add-Content -Path "local.properties" -Value "BOOTPAY_APP_ID=$env:BOOTPAY_APP_ID"

stages:
  - build

debug:
  stage: build
  script:
    - .\gradlew.bat assembleDebug
  artifacts:
    paths:
      - $env:ANDROID_PROJECT_DIR\app\build\outputs\apk\debug\app-debug.apk
  only:
    - develop