image: mcr.microsoft.com/dotnet/sdk:5.0 # Windows 기반 이미지 사용

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_PROJECT_DIR: "Drtaa-Android"

before_script:
  - $env:ANDROID_HOME = "C:\android-sdk"
  - $env:PATH += ";$env:ANDROID_HOME\tools;$env:ANDROID_HOME\platform-tools"
  
  # Android SDK 다운로드 및 설치 (이미 설치되어 있다면 이 부분은 생략 가능)
  - Invoke-WebRequest -Uri "https://dl.google.com/android/repository/commandlinetools-win-8512546_latest.zip" -OutFile "commandlinetools.zip"
  - Expand-Archive -Path "commandlinetools.zip" -DestinationPath "$env:ANDROID_HOME"
  - Move-Item "$env:ANDROID_HOME\cmdline-tools" "$env:ANDROID_HOME\latest"
  - $env:PATH += ";$env:ANDROID_HOME\latest\bin"
  
  - sdkmanager.bat "platforms;android-$env:ANDROID_COMPILE_SDK" "build-tools;$env:ANDROID_BUILD_TOOLS" "platform-tools"
  - cd $env:ANDROID_PROJECT_DIR
  - ./gradlew.bat --version # Gradle 버전 확인

  # local.properties 파일 생성
  - Add-Content -Path "local.properties" -Value "sdk.dir=$env:ANDROID_HOME"
  - Add-Content -Path "local.properties" -Value "NAVER_MAP_CLIENT_ID=$env:NAVER_MAP_CLIENT_ID"
  - Add-Content -Path "local.properties" -Value "NAVER_MAP_CLIENT_ID_MANIFEST=$env:NAVER_MAP_CLIENT_ID_MANIFEST"
  - Add-Content -Path "local.properties" -Value "NAVER_MAP_CLIENT_SECRET=$env:NAVER_MAP_CLIENT_SECRET"
  - Add-Content -Path "local.properties" -Value "NAVER_CLIENT_ID=$env:NAVER_CLIENT_ID"
  - Add-Content -Path "local.properties" -Value "NAVER_CLIENT_SECRET=$env:NAVER_CLIENT_SECRET"
  - Add-Content -Path "local.properties" -Value "GOOGLE_LOGIN_CLIENT_ID=$env:GOOGLE_LOGIN_CLIENT_ID"
  - Add-Content -Path "local.properties" -Value "TOUR_API_KEY=$env:TOUR_API_KEY"
  - Add-Content -Path "local.properties" -Value "BASE_URL=$env:BASE_URL"
  - Add-Content -Path "local.properties" -Value "MQTT_URL=$env:MQTT_URL"
  - Add-Content -Path "local.properties" -Value "BOOTPAY_APP_ID=$env:BOOTPAY_APP_ID"

stages:
  - build

debug:
  stage: build
  script:
    - ./gradlew.bat assembleDebug
  artifacts:
    paths:
      - $env:ANDROID_PROJECT_DIR/app/build/outputs/apk/debug/app-debug.apk
  only:
    - develop