image: ubuntu:20.04

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "9477386"
  ANDROID_PROJECT_DIR: "Drtaa-Android"
  DEBIAN_FRONTEND: "noninteractive"

before_script:
  - apt-get update && apt-get install -y wget unzip openjdk-17-jdk
  - mkdir -p android-sdk-linux
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - mv android-sdk-linux/cmdline-tools android-sdk-linux/latest
  - mkdir -p android-sdk-linux/cmdline-tools
  - mv android-sdk-linux/latest android-sdk-linux/cmdline-tools/
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
  - yes | sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-${ANDROID_COMPILE_SDK}" "platform-tools" "build-tools;${ANDROID_BUILD_TOOLS}"
  - cd $ANDROID_PROJECT_DIR
  - chmod +x ./gradlew
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo "NAVER_MAP_CLIENT_ID=$NAVER_MAP_CLIENT_ID" >> local.properties
  - echo "NAVER_MAP_CLIENT_ID_MANIFEST=$NAVER_MAP_CLIENT_ID_MANIFEST" >> local.properties
  - echo "NAVER_MAP_CLIENT_SECRET=$NAVER_MAP_CLIENT_SECRET" >> local.properties
  - echo "NAVER_CLIENT_ID=$NAVER_CLIENT_ID" >> local.properties
  - echo "NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET" >> local.properties
  - echo "GOOGLE_LOGIN_CLIENT_ID=$GOOGLE_LOGIN_CLIENT_ID" >> local.properties
  - echo "TOUR_API_KEY=$TOUR_API_KEY" >> local.properties
  - echo "BASE_URL=$BASE_URL" >> local.properties
  - echo "MQTT_URL=$MQTT_URL" >> local.properties
  - echo "BOOTPAY_APP_ID=$BOOTPAY_APP_ID" >> local.properties

stages:
  - build

debug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - $ANDROID_PROJECT_DIR/app/build/outputs/apk/debug/app-debug.apk
  only:
    - develop