image: ubuntu:20.04

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "9477386"
  ANDROID_PROJECT_DIR: "Drtaa-Android"
  DEBIAN_FRONTEND: "noninteractive"

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - $ANDROID_PROJECT_DIR/.gradle/

before_script:
  - apt-get update && apt-get install -y wget unzip openjdk-17-jdk
  - mkdir -p android-sdk-linux
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - mv android-sdk-linux/cmdline-tools android-sdk-linux/latest
  - mkdir -p android-sdk-linux/cmdline-tools
  - mv android-sdk-linux/latest android-sdk-linux/cmdline-tools/
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
  - yes | sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-${ANDROID_COMPILE_SDK}" "platform-tools" "build-tools;${ANDROID_BUILD_TOOLS}"
  - cd $ANDROID_PROJECT_DIR
  - chmod +x ./gradlew
  - ./gradlew --version
  - java -version
  - echo "ANDROID_HOME=$ANDROID_HOME"
  - echo "PATH=$PATH"
  - pwd
  - ls -la
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo "NAVER_MAP_CLIENT_ID=$NAVER_MAP_CLIENT_ID" >> local.properties
  - echo "NAVER_MAP_CLIENT_ID_MANIFEST=$NAVER_MAP_CLIENT_ID_MANIFEST" >> local.properties
  - echo "NAVER_MAP_CLIENT_SECRET=$NAVER_MAP_CLIENT_SECRET" >> local.properties
  - echo "NAVER_CLIENT_ID=$NAVER_CLIENT_ID" >> local.properties
  - echo "NAVER_CLIENT_SECRET=$NAVER_CLIENT_SECRET" >> local.properties
  - echo "GOOGLE_LOGIN_CLIENT_ID=$GOOGLE_LOGIN_CLIENT_ID" >> local.properties
  - echo "TOUR_API_KEY=$TOUR_API_KEY" >> local.properties
  - echo "BASE_URL=$BASE_URL" >> local.properties
  - echo "MQTT_URL=$MQTT_URL" >> local.properties
  - echo "BOOTPAY_APP_ID=$BOOTPAY_APP_ID" >> local.properties

stages:
  - build

debug:
  stage: build
  script:
    - cd $ANDROID_PROJECT_DIR
    - export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError"
    - ./gradlew assembleDebug --stacktrace --info
    - echo "Gradle build finished with exit code $?"
    - find . -name "*.apk"
  after_script:
    - cd $ANDROID_PROJECT_DIR
    - pwd
    - ls -R
    - if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then echo "APK file exists"; else echo "APK file does not exist"; fi
  artifacts:
    paths:
      - $ANDROID_PROJECT_DIR/app/build/outputs/apk/debug/app-debug.apk
    when: always
    expire_in: 1 week
  only:
    - develop