image: eclipse-temurin:17-jdk-focal

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "9477386"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - export ANDROID_HOME="${PWD}/android-home"
  - install -d $ANDROID_HOME
  - wget --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - pushd $ANDROID_HOME
  - unzip -d cmdline-tools cmdline-tools.zip
  - pushd cmdline-tools
  - mv cmdline-tools tools || true
  - popd
  - popd
  - export PATH=$PATH:${ANDROID_HOME}/cmdline-tools/tools/bin/
  - sdkmanager --version
  - yes | sdkmanager --licenses || true
  - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager "platform-tools"
  - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
  - chmod +x ./gradlew
  - echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
  - echo "NAVER_MAP_CLIENT_ID=\"$NAVER_MAP_CLIENT_ID\"" >> local.properties
  - echo "NAVER_MAP_CLIENT_ID_MANIFEST=$NAVER_MAP_CLIENT_ID_MANIFEST" >> local.properties
  - echo "NAVER_MAP_CLIENT_SECRET=\"$NAVER_MAP_CLIENT_SECRET\"" >> local.properties
  - echo "NAVER_CLIENT_ID=\"$NAVER_CLIENT_ID\"" >> local.properties
  - echo "NAVER_CLIENT_SECRET=\"$NAVER_CLIENT_SECRET\"" >> local.properties
  - echo "GOOGLE_LOGIN_CLIENT_ID=\"$GOOGLE_LOGIN_CLIENT_ID\"" >> local.properties
  - echo "TOUR_API_KEY=\"$TOUR_API_KEY\"" >> local.properties
  - echo "BASE_URL=\"$BASE_URL\"" >> local.properties
  - echo "MQTT_URL=\"$MQTT_URL\"" >> local.properties
  - echo "BOOTPAY_APP_ID=\"$BOOTPAY_APP_ID\"" >> local.properties

# lintDebug:
#   interruptible: true
#   stage: build
#   script:
#     - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDebug --no-daemon --parallel --max-workers=4 --stacktrace --info
  artifacts:
    paths:
      - app/build/outputs/

# debugTests:
#   interruptible: true
#   stage: test
#   script:
#     - ./gradlew -Pci --console=plain :app:testDebug