spring:
  main:
    web-application-type: servlet
    allow-circular-references: true
  profiles:
    active: prod
  server:
    port: 8080  # 서버 포트 설정
    forward-headers-strategy: framework
  logging:
    level:
      org.springframework.web: DEBUG  # 웹 요청 관련 디버그 로깅 (필요에 따라 조정)

  # Security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "497471459854-cqpdq1rh5hk12u5utkc0haecd1islhhg.apps.googleusercontent.com"
            client-secret: "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"
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email

          naver:
            client-id: "bIztVzGvXxyOPywhGHD4"
            client-secret: "9jpJ2CwkxX"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          kakao:
            client-id: "e057bf33b1cef097fd3963d25d62ee64"
            client-secret: "mVnx3elYNP969McFoB9Lm0qMiSdu2hgm"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정


  # JPA
  jpa:
    hibernate:
      ddl-auto: none  # 스키마 자동 생성 전략 (update, create, create-drop 등)
    show-sql: true  # SQL 쿼리 로깅 여부
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷팅 여부

  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/d211?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    hikari:
      maximum-pool-size: 10  # 커넥션 풀의 최대 크기 (필요에 따라 조정)

# JWT
jwt:
  secret-key: ssafy+gumi02+D211+ssafy+gumi02+D211+jwt+secretkey
  access-token:
    expiretime: 3600000 # 1시간
  refresh-token:
    expiretime: 2592000000 # 30일

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

# cors 설정
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600