# Use an official Eclipse Mosquitto image as a base
FROM eclipse-mosquitto:latest

# Expose the MQTT ports
EXPOSE 1883
EXPOSE 8883

# Copy the custom configuration file
COPY mosquitto.conf /mosquitto/config/mosquitto.conf

# Set the command to run Mosquitto
CMD ["mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
